name: PPA

on:
  push:
    tags:
      - "*.*.*"

jobs:
  ppa:
    uses: nikolareljin/ci-helpers/.github/workflows/ppa-deb.yml@production
    with:
      ppa_target: "ppa:nikolareljin/agentvault"
      signing_key_id: ${{ vars.GPG_KEY_ID }}
      prebuild_command: "make build"
    secrets:
      gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
      launchpad_ssh_private_key: ${{ secrets.LAUNCHPAD_SSH_KEY }}
